import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :metgauge, MetgaugeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
config :metgauge, MetgaugeWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "staging.moverapp.com", scheme: "https"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  debug_errors: true